version: '2'

services:
  ansible:
    build: .
    image: thejmazz/ansible
    working_dir: /root
    network_mode: host
    volumes:
      - ./hosts:/etc/ansible/hosts
      - ./plays:/root/plays
      - ./id_rsa:/root/.ssh/id_rsa
      - $SSH_AUTH_SOCK:/ssh-agent
    environment:
      - SSH_AUTH_SOCK=/ssh-agent

