version: '2'

services:
  ansible:
    build: .
    working_dir: /root
    volumes:
      - ./hosts:/etc/ansible/hosts
      - ./plays:/root/plays
      - ~/.ssh:/root/.ssh

networks:
  default:
    external:
      name: bridge

