---
- apt: name={{ item }}
  with_items:
    - libevent-dev
    - libncurses-dev
    - ifstat
- get_url:
    url: "https://github.com/tmux/tmux/releases/download/{{ tmux_version }}/tmux-{{ tmux_version }}.tar.gz"
    dest: /usr/local/src
  register: tmux_download
  vars:
    tmux_version: 2.5
- unarchive:
    src: "{{ tmux_download.dest }}"
    dest: /usr/local/src
    remote_src: yes
  register: tmux_unarchive
- shell: "./configure && make && make install"
  args:
    chdir: "/usr/local/src/tmux-2.5"
