---
- hosts: manager

  vars:
    ansible_python_interpreter: "/usr/bin/env python3"

  tasks:
    - shell: |
        BACKUP=/backup-$(date +"%Y-%m-%dT%H:%M:%SZ").tar.gz; \
        tar czfp $BACKUP \
        --exclude=/backup.tar.gz \
        --exclude=/home \
        --exclude=/media \
        --exclude=/dev \
        --exclude=/mnt \
        --exclude=/proc \
        --exclude=/sys \
        --exclude=/tmp \
        / || [ -e $BACKUP ]

