---
- hosts: all

  vars:
    ansible_python_interpreter: "/usr/bin/env python3"

  pre_tasks:
    - raw: apt-get install python-minimal aptitude -y # in case aptitude is not available
      ignore_errors: yes
    - apt: update_cache=yes upgrade=dist
    - apt: name=software-properties-common # for apt-add-repository
    - locale_gen: name=en_US.UTF-8
    - apt: name={{ item }}
      with_items:
        - curl
        - htop
        - zsh
        - mosh
        - cmake
        - ncdu
        # https://serverfault.com/a/706494/312364
        - libpam-systemd
        - dbus

  roles:
    - role: angstwad.docker_ubuntu
      docker_pkg_name: docker-ce=17.06.0*
      docker_opts: "--bip 10.100.0.1/24"
      pip_version_docker_compose: 1.14.0
      storage_driver: overlay2
    - role: tmux
    - role: neovim
    - role: yadm
    - role: glances
