---
- hosts: all

  vars:
    ansible_python_interpreter: "/usr/bin/env python3"

  vars_prompt:
    - name: username
      prompt: "Enter username"
      private: no
    - name: password
      prompt: "Enter password"
      private: yes
      confirm: yes
      encrypt: "sha512_crypt"
      salt_size: 8

  tasks:
    - user:
        name: "{{ username }}"
        password: "{{ password }}"
        shell: /bin/zsh
        update_password: on_create
        groups: [ 'sudo', 'docker' ]
    - authorized_key:
        user: "{{ username }}"
        state: present
        key: "{{ lookup('file', public_key) }}"
      when: public_key != ""
    - command: "yadm clone https://github.com/thejmazz/dottos.git --bootstrap"
      become: yes
      become_user: "{{ username }}"

